#### Dataset 1 (18700 entries)

In [2]:
import pandas as pd

# Load the dataset
df = pd.read_csv('Dataset1.csv')

# Drop the 'Vehicle' column
df.drop('Vehicle ', axis=1, inplace=True)

# Calculate mean, median, and mode for each column
mean_values = df.mean()
median_values = df.median()
mode_values = df.mode().iloc[0]  # mode() returns a DataFrame, take the first row

print("Mean Values:")
print(mean_values)
print("\nMedian Values:")
print(median_values)
print("\nMode Values:")
print(mode_values)

Mean Values:
RAM                 56.230942
storage             53.200445
Trustfactor         55.130749
Distance            50.382802
TransmissionRate    55.453357
Eligible            54.079659
dtype: float64

Median Values:
RAM                 56.168750
storage             53.028125
Trustfactor         55.000000
Distance            50.300000
TransmissionRate    55.555556
Eligible            54.023843
dtype: float64

Mode Values:
RAM                 95.487500
storage             31.312500
Trustfactor         42.000000
Distance            20.200000
TransmissionRate    40.740741
Eligible            41.966204
Name: 0, dtype: float64

In [2]:
import pandas as pd
from tabulate import tabulate

# Load the dataset
df = pd.read_csv('Dataset1.csv')

# Drop the 'Vehicle' column
df.drop('Vehicle ', axis=1, inplace=True)

# Calculate summary statistics
summary_statistics = df.describe()

# Calculate mode (pandas mode() might return multiple rows if there is a tie, take the first row)
mode_values = df.mode().iloc[0]

# Add the mode to the summary statistics
summary_statistics.loc['mode'] = mode_values

summary_statistics

,RAM,storage,Trustfactor,Distance,TransmissionRate,Eligible
count,18700.000000,18700.000000,18700.000000,18700.000000,18700.000000,18700.000000
mean,56.230942,53.200445,55.130749,50.382802,55.453357,54.079659
std,25.276585,26.928076,26.200357,28.501608,26.634841,11.964752
min,12.500000,6.250000,10.000000,1.500000,11.111111,14.623472
25%,34.462500,30.217188,33.000000,25.700000,33.333333,45.800069
50%,56.168750,53.028125,55.000000,50.300000,55.555556,54.023843
75%,78.075000,76.520313,78.000000,75.100000,77.777778,62.355278
max,100.000000,100.000000,100.000000,100.000000,100.000000,94.893009
mode,95.487500,31.312500,42.000000,20.200000,40.740741,41.966204

In [3]:
import scipy.stats as stats

mean = 54.079659
std_dev = 11.964752

# Z-scores for 30th and 70th percentiles
z_30th = stats.norm.ppf(0.3)  # Percent point function (inverse of cdf)
z_70th = stats.norm.ppf(0.7)

# Calculate x and y
x = mean + z_30th * std_dev
y = mean + z_70th * std_dev

x, y

(47.805336916775445, 60.353981083224554)

In [9]:
import pandas as pd
from tabulate import tabulate

# Load the dataset
df = pd.read_csv('Dataset1.csv')

# Drop the 'Vehicle' column
df.drop('Vehicle ', axis=1, inplace=True)

# Calculate summary statistics
summary_statistics = df.describe()

# Calculate mode (pandas mode() might return multiple rows if there is a tie, take the first row)
mode_values = df.mode().iloc[0]

# Add the mode to the summary statistics
summary_statistics.loc['mode'] = mode_values

# Print the table using tabulate for better formatting
print(tabulate(summary_statistics, headers='keys', tablefmt='pretty'))

+-------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+
|       |        RAM        |      storage       |    Trustfactor     |     Distance      |  TransmissionRate  |      Eligible      |
+-------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+
| count |      18700.0      |      18700.0       |      18700.0       |      18700.0      |      18700.0       |      18700.0       |
| mean  | 56.23094184491979 | 53.200445187165776 | 55.130748663101606 | 50.38280213903743 | 55.45335710047486  | 54.07965898702246  |
|  std  | 25.27658487251446 | 26.928075954725834 | 26.200356957832497 | 28.50160750771764 | 26.634841020697518 | 11.964751587428534 |
|  min  |       12.5        |        6.25        |        10.0        |        1.5        |    11.11111111     |    14.62347222     |
|  25%  |      34.4625      |     30.2171875     |        33.0        |       25.7        |    33.33333333     |   45.8000694475    |
|  50%  |     56.16875      |     53.028125      |        55.0        |       50.3        |    55.55555556     |    54.023842595    |
|  75%  |      78.075       |     76.5203125     |        78.0        |       75.1        |    77.77777778     |   62.3552777775    |
|  max  |       100.0       |       100.0        |       100.0        |       100.0       |       100.0        |    94.89300926     |
| mode  |      95.4875      |      31.3125       |        42.0        |       20.2        |    40.74074074     |     41.9662037     |
+-------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+

#### Dataset 2 (4600 entries)

In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv('Dataset2.csv')

# Drop the 'Vehicle' column
df.drop('Vehicle ', axis=1, inplace=True)

# Calculate mean, median, and mode for each column
mean_values = df.mean()
median_values = df.median()
mode_values = df.mode().iloc[0]  # mode() returns a DataFrame, take the first row

print("Mean Values:")
print(mean_values)
print("\nMedian Values:")
print(median_values)
print("\nMode Values:")
print(mode_values)

Mean Values:
RAM                 56.356685
storage             53.270170
Trustfactor         55.682826
Distance            49.938978
TransmissionRate    55.483897
Eligible            54.146511
dtype: float64

Median Values:
RAM                 56.450000
storage             53.512500
Trustfactor         56.000000
Distance            49.000000
TransmissionRate    55.555556
Eligible            54.301898
dtype: float64

Mode Values:
RAM                 44.412500
storage              7.218750
Trustfactor         90.000000
Distance            80.400000
TransmissionRate    33.333333
Eligible            39.180093
Name: 0, dtype: float64

In [10]:
import pandas as pd
from tabulate import tabulate

# Load the dataset
df = pd.read_csv('Dataset2.csv')

# Drop the 'Vehicle' column
df.drop('Vehicle ', axis=1, inplace=True)

# Calculate summary statistics
summary_statistics = df.describe()

# Calculate mode (pandas mode() might return multiple rows if there is a tie, take the first row)
mode_values = df.mode().iloc[0]

# Add the mode to the summary statistics
summary_statistics.loc['mode'] = mode_values

# Print the table using tabulate for better formatting
print(tabulate(summary_statistics, headers='keys', tablefmt='pretty'))

+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+
|       |        RAM         |      storage      |    Trustfactor     |      Distance      |  TransmissionRate  |      Eligible      |
+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+
| count |       4600.0       |      4600.0       |       4600.0       |       4600.0       |       4600.0       |       4600.0       |
| mean  | 56.356684782608696 | 53.27016983695652 | 55.682826086956524 | 49.93897826086957  | 55.48389694040652  | 54.14651118169565  |
|  std  | 25.34031414291653  | 27.00485805070628 | 26.327500007297292 | 28.641751719335158 | 26.605700644026044 | 12.183029175141556 |
|  min  |        12.5        |      6.2875       |        10.0        |        1.5         |    11.11111111     |    15.05972222     |
|  25%  |       34.525       |     29.565625     |        33.0        |        24.9        |    33.33333333     |   45.6544097225    |
|  50%  |       56.45        |      53.5125      |        56.0        |        49.0        |    55.55555556     |    54.30189815     |
|  75%  |      78.8875       |     76.86875      |       78.25        |        74.8        |    77.77777778     |    62.426412035    |
|  max  |       100.0        |     99.96875      |       100.0        |       100.0        |       100.0        |      93.04375      |
| mode  |      44.4125       |      7.21875      |        90.0        |        80.4        |    33.33333333     |    39.18009259     |
+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+

#### Dataset 3 (250 entries)

In [4]:
import pandas as pd

# Load the dataset
df = pd.read_csv('Dataset3.csv')

# Drop the 'Vehicle' column
df.drop('Vehicle ', axis=1, inplace=True)

# Calculate mean, median, and mode for each column
mean_values = df.mean()
median_values = df.median()
mode_values = df.mode().iloc[0]  # mode() returns a DataFrame, take the first row

print("Mean Values:")
print(mean_values)
print("\nMedian Values:")
print(median_values)
print("\nMode Values:")
print(mode_values)

Mean Values:
RAM                 56.961150
storage             54.510575
Trustfactor         54.632000
Distance            52.986000
TransmissionRate    55.792593
Eligible            54.976464
dtype: float64

Median Values:
RAM                 57.300000
storage             52.603125
Trustfactor         52.000000
Distance            55.750000
TransmissionRate    55.555556
Eligible            54.547824
dtype: float64

Mode Values:
RAM                 12.900000
storage              7.568750
Trustfactor         97.000000
Distance            37.200000
TransmissionRate    33.333333
Eligible            23.118704
Name: 0, dtype: float64

In [11]:
import pandas as pd
from tabulate import tabulate

# Load the dataset
df = pd.read_csv('Dataset3.csv')

# Drop the 'Vehicle' column
df.drop('Vehicle ', axis=1, inplace=True)

# Calculate summary statistics
summary_statistics = df.describe()

# Calculate mode (pandas mode() might return multiple rows if there is a tie, take the first row)
mode_values = df.mode().iloc[0]

# Add the mode to the summary statistics
summary_statistics.loc['mode'] = mode_values

# Print the table using tabulate for better formatting
print(tabulate(summary_statistics, headers='keys', tablefmt='pretty'))

+-------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|       |       RAM        |      storage       |    Trustfactor     |      Distance      |  TransmissionRate  |      Eligible      |
+-------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
| count |      250.0       |       250.0        |       250.0        |       250.0        |       250.0        |       250.0        |
| mean  |     56.96115     | 54.510574999999996 |       54.632       |       52.986       | 55.792592592599995 | 54.976463518920006 |
|  std  | 25.8591511188758 | 25.967935430211924 | 25.959355317766583 | 28.49290061650742  | 25.806631472930494 | 12.213190412080344 |
|  min  |     12.5375      |      7.56875       |        10.0        |        1.8         |    11.11111111     |     23.1187037     |
|  25%  |    33.971875     |      31.39375      |        32.0        | 29.775000000000002 |    33.33333333     |   47.2210763875    |
|  50%  |       57.3       |     52.603125      |        52.0        |       55.75        |    55.55555556     |    54.547824075    |
|  75%  |    80.284375     |     76.2828125     |        78.0        | 78.67500000000001  |    77.77777778     |    63.17607639     |
|  max  |      99.85       |      99.93125      |       100.0        |        98.8        |       100.0        |    86.30231481     |
| mode  |       12.9       |      7.56875       |        97.0        |        37.2        |    33.33333333     |     23.1187037     |
+-------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+